# Generated by Django 5.2.1 on 2025-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelessoncontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson'),
        ),
    ]
