# Generated by Django 5.2.1 on 2025-06-06 05:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidesSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='GuidesAndSupport')),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created']},
        ),
    ]
