# Generated by Django 5.2.1 on 2025-06-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guidessupport_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidessupport',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
