# Generated by Django 5.2.1 on 2025-06-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_guidessupport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='home')),
            ],
        ),
        migrations.RemoveField(
            model_name='guidessupport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='guidessupport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='app_language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='listening_language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme_mode',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GuideSupportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='GuidesAndSupport')),
                ('video', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guidessupport')),
            ],
        ),
        migrations.CreateModel(
            name='LessonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lesson')),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MockTestTaken', models.PositiveIntegerField(default=0)),
                ('LeftMockTest', models.CharField(choices=[('Limited', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='Limited', max_length=20)),
                ('PracticeCompleted', models.CharField(max_length=100)),
                ('QuestionAnswered', models.CharField(max_length=100)),
                ('CorrectAnswered', models.CharField(max_length=100)),
                ('WrongAnswered', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
