# Generated by Django 5.2.1 on 2025-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_theorycategory_user_unit_lesson_delete_theory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('audio', models.CharField(max_length=150)),
                ('type', models.TextField()),
                ('option', models.JSONField()),
            ],
        ),
    ]
