# Generated by Django 5.2.1 on 2025-06-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homepage_remove_guidessupport_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonList',
            new_name='LessonContent',
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='LeftMockTest',
            field=models.CharField(choices=[('Limited', 'Limited'), ('Unlimited', 'Unlimited')], default='Limited', max_length=20),
        ),
    ]
