# Generated by Django 5.2.1 on 2025-06-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_lessonlist_lessoncontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=' '),
        ),
    ]
