# Generated by Django 5.2.1 on 2025-06-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_question_option_question_chapter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuideSupportList',
            new_name='GuideSupportContent',
        ),
    ]
