# Generated by Django 5.2.1 on 2025-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_guidesupportlist_guidesupportcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidesupportcontent',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
