# Generated by Django 5.2.1 on 2025-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_guidesupportcontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidessupport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guidesupportcontent',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guidesupportcontent',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
