# Generated by Django 5.2.1 on 2025-06-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_guidessupport_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='glossary',
            field=models.TextField(default='', max_length=200),
        ),
    ]
