# Generated by Django 5.2.1 on 2025-06-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_practicequestion_practiceoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='type',
            field=models.CharField(choices=[('practice', 'practice'), ('mockTest', 'mockTest'), ('freeMockTest', 'freeMockTest')], default='practice', max_length=50),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
