# Generated by Django 5.2.1 on 2025-06-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_practicequestion_type_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeQuestion',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='PracticeOption',
            new_name='QuestionOption',
        ),
    ]
