# Generated by Django 5.2.1 on 2025-06-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_practicequestion_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='user',
        ),
    ]
