# Generated by Django 5.2.1 on 2025-06-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_chapter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
    ]
