# Generated by Django 5.2.1 on 2025-06-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_lesson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated',
        ),
    ]
