# Generated by Django 5.2.1 on 2025-06-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_lesson_status_remove_lesson_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidessupport',
            name='status',
        ),
    ]
