# Generated by Django 5.2.1 on 2025-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidesupportcontent',
            name='glossary',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
