# Generated by Django 5.2.1 on 2025-07-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='chapter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.chapter'),
        ),
    ]
