# Generated by Django 5.2.1 on 2025-07-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_lessoncontent_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='chapter',
        ),
    ]
