# Generated by Django 5.2.1 on 2025-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_lessoncontent_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='glossary',
            field=models.TextField(default=list),
        ),
    ]
