# Generated by Django 5.2.1 on 2025-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_lessoncontent_glossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesupportcontent',
            name='glossary',
            field=models.TextField(blank=True, default=list),
        ),
    ]
