# Generated by Django 5.2.1 on 2025-09-05 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_guidesupportcontent_glossary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='glossary',
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to='main.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='glossary',
            field=models.ManyToManyField(blank=True, related_name='lesson_contents', to='main.glossary'),
        ),
    ]
