# Generated by Django 5.2.1 on 2025-09-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_lessoncontent_glossary_glossary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='glossary',
        ),
        migrations.DeleteModel(
            name='Glossary',
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='glossary',
            field=models.JSONField(default=list),
        ),
    ]
