# Generated by Django 5.2.1 on 2025-09-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_lessoncontent_glossary_delete_glossary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='glossary',
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lesson_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to='main.lessoncontent')),
            ],
            options={
                'verbose_name_plural': 'Glossaries',
            },
        ),
    ]
