# Generated by Django 5.2.1 on 2025-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_lessoncontent_glossary_glossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
