# Generated by Django 5.2.1 on 2025-09-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_questionglossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidesSupportGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to='main.guidessupport')),
            ],
            options={
                'verbose_name_plural': 'Glossaries',
            },
        ),
    ]
