# Generated by Django 5.2.1 on 2025-09-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_guidessupportglossary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidesupportcontent',
            name='glossary',
        ),
        migrations.AlterField(
            model_name='guidessupportglossary',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to='main.guidesupportcontent'),
        ),
        migrations.AlterField(
            model_name='guidesupportcontent',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
