# Generated by Django 5.2.1 on 2025-09-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionglossary',
            old_name='definition',
            new_name='description',
        ),
    ]
