# Generated by Django 5.2.1 on 2025-06-14 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1_week', '1 Week Access'), ('1_month', '1 Month Access'), ('lifetime', 'Lifetime Access')], help_text="Unique name for the subscription plan (e.g., '1_week', 'lifetime')", max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the subscription plan.', max_digits=6)),
                ('duration_days', models.IntegerField(blank=True, help_text='Duration of the plan in days. Null for lifetime access.', null=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated list of features included in this plan.')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the subscription started.')),
                ('end_date', models.DateTimeField(blank=True, help_text='The date and time the subscription ends. Null for lifetime.', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Indicates if the subscription is currently active.')),
                ('last_renewed', models.DateTimeField(blank=True, help_text='Date of last successful renewal (for recurring plans).', null=True)),
                ('plan', models.ForeignKey(help_text='The subscription plan the user is subscribed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(help_text='The user associated with this subscription.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
