# Generated by Django 5.2.1 on 2025-09-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='device_id',
            field=models.CharField(blank=True, help_text='Information about the device used for subscription (if applicable).', max_length=255),
        ),
    ]
